// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh8PiuKYrjFCEsTnAo16GPb7t9pdI1TG0',
    appId: '1:550600871844:web:6c3c3c92ec9b55c9407b31',
    messagingSenderId: '550600871844',
    projectId: 'raysize',
    authDomain: 'raysize.firebaseapp.com',
    storageBucket: 'raysize.firebasestorage.app',
    measurementId: 'G-BS8344DPFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDuJ4iXM00cc5V0MLLaYUngoLHHnjZgBo',
    appId: '1:550600871844:android:dd520bbaf7b02b3f407b31',
    messagingSenderId: '550600871844',
    projectId: 'raysize',
    storageBucket: 'raysize.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtmW9Kkh6A1qpirfUz0Yads_3c_3MPQmE',
    appId: '1:550600871844:ios:b7ec5e2930ad7e36407b31',
    messagingSenderId: '550600871844',
    projectId: 'raysize',
    storageBucket: 'raysize.firebasestorage.app',
    iosBundleId: 'com.example.raysize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtmW9Kkh6A1qpirfUz0Yads_3c_3MPQmE',
    appId: '1:550600871844:ios:b7ec5e2930ad7e36407b31',
    messagingSenderId: '550600871844',
    projectId: 'raysize',
    storageBucket: 'raysize.firebasestorage.app',
    iosBundleId: 'com.example.raysize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh8PiuKYrjFCEsTnAo16GPb7t9pdI1TG0',
    appId: '1:550600871844:web:f89ceed9c6753000407b31',
    messagingSenderId: '550600871844',
    projectId: 'raysize',
    authDomain: 'raysize.firebaseapp.com',
    storageBucket: 'raysize.firebasestorage.app',
    measurementId: 'G-SF3P7QN2CK',
  );
}
